spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: ryansgrt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: school-service
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
