spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: ryansgrt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: student-service
server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
